---
bosh:
  cmd: bosh2
  env: tt-stg02
  cf-dep: cf-da0ba81cb255ad93a508
  cfdot-dc: diego_cell/0
cf:
  cmd: cf
container-port-whitelist:
 - 22
 - 2222
host-port-whitelist: []
service-whitelist:
 - T-Logger